### ISSUE TITLE
kernelmatrix(k, X, Y) calculates full matrix, not only upper-right triangle as commented

### ISSUE THREAD

**Issue by st--** [trthatcher/MLKernels.jl#13]
Now the question is, are there going to be any kernels which are non-symmetric, for which k(x, y) != k(y, x)? If not, then kernelmatrix(k, X, Y) should only calculate half the matrix, as already the case for kernelmatrix(k, X) [which calculates kernelmatrix(k, X, X)].

On second thought, why is there a special case for kernelmatrix(k, X, X)? Should be the same code as for kernelmatrix(k, X, Y)...

**Comment by trthatcher** [comment]
The main reason I have a special case for k(X,X) is to take advantage of sryk! which is more efficient than gemm!. In the case of scalar and euclidean distance kernels... symmetry will definitely be the case for the kernel matrix, so we should take advantage of that (divide computations by two almost). 

Generally speaking, it probably makes sense to have my fallback routine to not assume symmetry. I will have to provision for that, but will still assume symmetry for the kernels that have been explicitly been accounted for. Good catch!

**Comment by trthatcher** [comment]
I just realized I misread this. 

kernelmatrix(X,Y) is not required to be symmetric, kernelmatrix(X) is.

**Comment by trthatcher** [comment]
Closing unless you have an objection...
