### ISSUE TITLE
N vs. T

### ISSUE THREAD

**Issue by st--** [trthatcher/MLKernels.jl#15]
How useful is it to basically duplicate have the code to allow both row-wise and column-wise data matrices ? From an implementation point of view it'd be a lot simpler to just decide on one, and require users to call e.g. kernelmatrix(k, X', Y') when needed, which is a one-off overhead.

The only difference is whether the access is X[i,:] and Y[j,:] or X[:,i] and Y[:,j]... so I played around with macros and came up with one which takes a condition, a tuple of symbols, and a code block and transforms all array references to objects listed in the tuple of symbols (84ca8bffcc825aaea48708b4d8fc9e9c6984c446, 1564f8a3c4a68ac97bcd5eeda4464a6120fa4e7b). But that doesn't work so well for the cases where you have e.g. N_sqdist and T_sqdist...

**Comment by trthatcher** [comment]
If we were just computing the kernel matrix, I would say do it because it's too easy not to (just a flag for BLAS). 

However, your features are much more involved. It's well past the point where it's useful/easy to add. I'm in agreement... drop it, it's not adding enough value for the level of effort.

**Comment by trthatcher** [comment]
Actually, hold that thought... Let me take a look at things.

**Comment by trthatcher** [comment]
Upon review, I'd like to keep this feature. I think it's relatively straight forward to maintain and only impacts a small part of the code. I just pushed a small change change that reduces code redundancy at the cost of a very minor increase in complexity.

I'd like this package to mesh well with anyone's project. If someone has to call the same function kernelmatrix() function over and over, forcing a transpose is far from one off.

For the record, I don't mind being responsible for ensuring the transpose version of any code will work if you want to implement the non-transposed version.
