### ISSUE TITLE
Re-implementing Base functions

### ISSUE THREAD

**Issue by st--** [trthatcher/MLKernels.jl#16]
In one of your recent commits you made use of (Base.)scale!() which I hadn't come across before, but it looks like it's basically the same functionality as gdmm!/dgmm! in matrixfunctions.jl - the only difference is that the Base version doesn't use `@inbounds`... does that macro make things so much faster that it's worth keeping an in-package version of matrix-vector scaling ?

**Comment by trthatcher** [comment]
No.

If something is re-implemented from Base, it was the result of an oversight.
