### ISSUE TITLE
Only integer exponents?

### ISSUE THREAD

**Issue by st--** [trthatcher/MLKernels.jl#17]
Does the exponent e.g. for PowerKernel need to be integer? Can it not interpolate with real exponents?

**Comment by trthatcher** [comment]
Most kernels were raided from this [blog](http://crsouza.com/2010/03/kernel-functions-for-machine-learning-applications/) to play around with.... not necessarily checked.

Anyway, I just read the paper. Power kernel is conditionally positive definite and should be computed as sqdist(x,y)^gamma where gamma in (0,1].

CPD kernels aren't closed under point-wise multiplication like positive definite kernels are (although, they are for addition). Perhaps a warning should be included when computing the product of a CPD kernel with any other kernel....

**Comment by trthatcher** [comment]
Fixed!
