### ISSUE TITLE
Periodic Kernel does not appear to be a Squared Distance kernel

### ISSUE THREAD

**Issue by trthatcher** [trthatcher/MLKernels.jl#20]
I was trying to find some documentation on the periodic kernel. In all the papers I look at, it seems like the sin() function is applied to the element-wise distances and squared rather than taking the squared sine of the distance.

sum sin(xi - yi)^2 for all i

rather than sin(||x-y||)^2

Here's a paper for example:

http://jmlr.org/proceedings/papers/v33/hajighassemi14.pdf

**Comment by st--** [comment]
That makes more sense, thanks. I'd only ever come across it in the 1D case, and didn't think too much about how to generalise it. Will need to do some more of that to see how to best fit it in.

**Comment by trthatcher** [comment]
Using sin(a-b)^2 = (1 - cos(2a - 2b))/2 = (1 - cos(2a)cos(2b) - sin(2a)sin(2b))/2 means we can express that formula as two dot products.

∑ᵢ sin(xᵢ - yᵢ)² = (n - <cos(2x),cos(2y)> - <sin(2x),sin(2y)>)/2

So in julia that's something like `exp(-size(X,2) .+ cos(2X)*cos(2Y) + sin(2X)*sin(2Y))`

**Comment by st--** [comment]
It's probably faster to just explicitly code a loop over i and accumulate in a local variable. But I was thinking of the interface - it's a kind of ARD kernel, but unlike the ones already there it's not just taking a non-ARD kernel and adding a layer in between (kappa(sqdist(x,y,w)) instead of kappa(sqdist(x,y))), it's a bit more internal than that...

**Comment by trthatcher** [comment]
For vector `kernel(x,y)` the accumulator method will definitely be faster. However, I _highly_ doubt that will work for `kernelmatrix(X,Y)`... BLAS is king here.

I think PeriodicKernel deserves its own class/type. However, I think we can still maintain ARD as a separate wrapper.
