### ISSUE TITLE
Why split up test_standardkernels?

### ISSUE THREAD

**Issue by st--** [trthatcher/MLKernels.jl#21]
The kernels are all very similar in their tests - wouldn't splitting it up risk missing some tests for some of them / testing them vaguely differently? It's a lot of code duplication for which I can't see the gain... maybe you've got a good reason though ? Mainly curious.

**Comment by trthatcher** [comment]
Mostly for modularity... I want a 1:1 correspondence between unit tests and features (n:1 or m:1 is annoying to maintain). I was going to figure out exactly what tests I want to run (per kernel class) and then define functions for common pieces of the workflow to reduce the code duplication as you pointed out. With that in mind, it might make sense to include the kappa_d\* functions in the standard kernel tests, then.

**Comment by st--** [comment]
Generally I agree that modularity is a good thing, but considering how similar the various kernel types are to each other (the only part which really is different is the bit which compares the value of kappa(k, u) to the test reference value, where u is sqdist(x,y) or dot(x,y) depending on the kernel type), I'm still not quite convinced. I do agree with moving test specifics into functions though.

Testing derivatives is quite different from just checking that a function returns the value you expect. As such I'd very much like to keep the derivatives in their own test file..

**Comment by trthatcher** [comment]
I restructured the Standard Kernel test code in such a way that I think we'll both be happy.
