### ISSUE TITLE
Definity of kernels

### ISSUE THREAD

**Issue by st--** [trthatcher/MLKernels.jl#26]
I had assumed the Sigmoid kernel was c.p.d., but according to the [paper I just read](http://vip.uwaterloo.ca/files/publications/Carrington%20et%20al%20-%20A%20New%20Mercer%20Sigmoid%20Kernel.pdf) about the Mercer Sigmoid kernel apparently that's only true for some parameter values, depending on the data set... so I suppose we should have iscondposdef(::SigmoidKernel) = false?

Also, I think we might've been working with `isposdef(::Kernel)` meaning "positive semi-definite", but Base.isposdef is "strictly positive definite" (e.g. isposdef(0) = false...), and if we extend a Base function we should follow that. For kernels it doesn't seem to make much difference whether it's positive semi-definite or strictly positive definite, so maybe move to our own function? We could have ismercer()... as positive semi-definity is sufficient and necessary for a kernel being a Mercer kernel.

**Comment by trthatcher** [comment]
Interesting. I think an `ismercer` function is good idea - pragmatically speaking, most users would only need to know if the kernel is a Mercer kernel or not. Some algorithms require the kernel to be Mercer for convergence while others do not.

I made the changes in the last commit: 50d68d80bfc89c3cd22694a0302ca81bcd82207b
