### ISSUE TITLE
Approach to derivatives

### ISSUE THREAD

**Issue by trthatcher** [trthatcher/MLKernels.jl#27]
Types can be parameterized by symbols, which means we can take a different approach to derivatives. I've included a [gist](https://gist.github.com/trthatcher/acd86f5a9b911737d419) to illustrate how we could take advantage of this ("Approach 2") 

It would cut down on the number of functions and it seems to perform better on my machine (and definitely no worse).

**Comment by st--** [comment]
Nice :-) very neat. The only thing I'm not so sure about is how that would generalise to the composite kernels (have a look at my recent changes; I finally got around to finish them up properly). On the machine on which I'm developing, the difference in timing is ~6.7 for the old version vs ~6.4 for the symbol-parameterized version in your gist... not sure if the small speedup would be worth the coding hassle for that.

**Comment by trthatcher** [comment]
Haha, I took a look... and I appreciate the complexity of actually implementing composite kernel derivative. Good stuff! 

But yeah... I don't see a straight forward change either. No worries, just an idea.
