### ISSUE TITLE
ARD parameter (weights) derivative

### ISSUE THREAD

**Issue by st--** [trthatcher/MLKernels.jl#30]
Just realised that `kernelmatrix_dp` was missing, and added it in ab3c09258fdcc322f0748ac9467f0b8ac86f518c -- piggy-backing on `kernelmatrix` seemed easiest. The only issue with this is that, currently, `kernel_dp(k::ARD, :weights, x, y)` returns an array with the length of `k.weights`. From a computational POV it makes sense to calculate all dk/dw[i]s at once (and usually you'd want all derivatives, not just one of them, I think), but from an interface/API POV it would be better if `kernel_dp` always returned a scalar... how to reconcile that ?

**Comment by kskyten** [comment]
The current implementation doesn't seem to have ARD kernels so this issue is stale. Are there plans to include them again?

**Comment by trthatcher** [comment]
I would say no unless they are required for a specific reason.
