### ISSUE TITLE
@inbounds

### ISSUE THREAD

**Issue by st--** [trthatcher/MLKernels.jl#31]
Various functions, particularly in vectorfunctions.jl and kernelderiv.jl, use `@inbounds` without making sure all the arguments have the right length etc. Is this fine, because we know how we call them, and we do check array dimensions etc. in the parent routines? Or should we add additional bounds checks in there?

**Comment by trthatcher** [comment]
I think it's reasonable to not check the `@inbounds` on the in-place calculations - it works under the assumption that you are correctly pointing to the data structures (similar to how BLAS works as an external library). Further, it's exclusively used as an internal method. As longs as there's a check in the parent methods, it should be fine.

The derived functions `scprodmatrix!` (weighted) and `sqdistmatrix!` fall back to the base unweighted `scprodmatrix!` which checks ALL the dimensions before passing to BLAS. We know the final step makes a thorough check before doing any kind of writing - so I think it's safe to not require checks here.

As for the rest... checks are good to have.
