### ISSUE TITLE
Consistency in Exceptions: ArgumentError vs DimensionMismatch

### ISSUE THREAD

**Issue by st--** [trthatcher/MLKernels.jl#35]
`kernelmatrix!` for StandardKernel throws ArgumentError, `kernelmatrix!` for SquaredDistanceKernel or ScalarProductKernel throws DimensionMismatch (by `scprodmatrix!`/`sqdistmatrix!`). `matrix_prod!` and `matrix_sum!` for generic Arrays call error(), but for matrices with is_upper argument the former throws DimensionMismatch and the latter throws ArgumentError. I think this should all be made a bit more consistent.

Is there a specific reason to use error() rather than throw(<some exception>) in some cases ?

(NB. there should be `@test_throw`s as well, which I'm about to add.)

**Comment by st--** [comment]
For no apparent reason, DimensionMismatch() only takes an ASCIIString, not a String (at least in Julia 0.3)... so I had to leave some of the throw()s as ArgumentError() because of that...

**Comment by trthatcher** [comment]
Hahaha... whaaaaaa? That's odd with regards to ASCII only.

We could just use `error` since our error messages are pretty descriptive? I'm indifferent! How would you like to do it?
