### ISSUE TITLE
Use of triangular dispatch invalid

### ISSUE THREAD

**Issue by IainNZ** [trthatcher/MLKernels.jl#37]
This definition for ARD seems to invalid in Julia 0.4, and I think should be invalid in 0.3 too but might not be due to a change.

https://github.com/trthatcher/MLKernels.jl/blob/c1532ce1d3b43806664296b82b4a0bd0b281190c/src/kernels.jl#L62

```
immutable ARD{T<:FloatingPoint,K<:StandardKernel{T}} <: SimpleKernel{T}
```

In particular the `K` part. I can't find exactly where it was changed, but here is related discussion

https://github.com/JuliaLang/julia/issues/6620
https://github.com/JuliaLang/julia/issues/3766
https://github.com/JuliaLang/julia/issues/8974#issuecomment-62552208

I'm a bit confused on how this all works internally, might be worth posting on julia-users if you want to get it working on 0.4 at some point.

**Comment by trthatcher** [comment]
Fixed.
