### ISSUE TITLE
kernel function

### ISSUE THREAD

**Issue by joshualeond** [trthatcher/MLKernels.jl#41]
I just started using your latest version of MLKernels.  I'm having an issue which may just be a syntax problem on my end.  I'm attempting to use the kernel function like I have in the past but here's the result:

``` julia
julia> kernel(GaussianKernel(), 2., 4.)
```

```
ERROR: type KernelComposition has no field k
 in kernel at /Users/joshualeond/.julia/v0.4/MLKernels/src/kernelfunction.jl:14
```

I usually use the kernel to compare arrays and have the same result except the error is at line 16.  The version that isn't working for me is v0.1.0+ which I cloned from Github and the previous version I was using was v0.1.0 installed from Metadata.

**Comment by trthatcher** [comment]
Hey! Sorry about that. I had made a number of changes in the back end and hadn't refreshed the front end yet, so the latest `master` branch was not quite functional.

The latest version should work for all the standard kernels like the Gaussian Kernel (but I haven't tested products or linear combinations of kernels). I'll close this issue when the master branch is back at 100%.

``` julia
julia> kernel(GaussianKernel(), 2., 4.)
0.01831563888873418
```

**Comment by joshualeond** [comment]
Great, thanks for the updates!
