### ISSUE TITLE
MLKernels with julia v0.5

### ISSUE THREAD

**Issue by Mattriks** [trthatcher/MLKernels.jl#43]
`MLKernels` is nice, but there are a few issues when using with julia 0.5.
Here is what I've found:
- In `kernelapproximation.jl`: replace `Base.blasfunc` with `Base.LinAlg.BLAS.@basefunc` and `chksquare` with `checksquare`
- In `meta.jl`: replace `super` with `supertype`
- In`pairwise.jl`: replace text like `i = store_upper ? (1:j) : (j:n)` with `i = (store_upper ? (1:j) : (j:n))`
- In `kernelfunctions.jl`: in the first 4 `call` statements, there is the issue of adding methods to an abstract type in Julia 0.5 e.g. sisl/BayesNets.jl#28 . What functionality in `MLKernels` would be lost if these statements were excluded?

**Comment by trthatcher** [comment]
Thanks for the review! There's definitely a couple items that will need fixing.

I've actually got a major version hiding in the dev branch that I had not merged yet. I was going to update it for 0.5, merge and do a release. I don't have an expected completion date, however.

**Comment by kskyten** [comment]
Should this issue be closed? This seems outdated. Did you merge the changes already?

**Comment by trthatcher** [comment]
Master should work just fine with Julia 0.5 now, so I'll close the issue.
