### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by gdkrmr** [trthatcher/MLKernels.jl#44]
The following code shaves off more than 0.5 seconds when X has `20_000` columns and `10` rows:

```julia
n = 20000
x = randn(10, n)

function gauss{T}(X::Matrix{T}, alpha::T)
    n = size(X, 2)
    xy = LinAlg.BLAS.syrk('U', 'T', one(T), X)
    x2 = [ sum(X[:, i] .^ 2) for i in 1:n ]
    
    LinAlg.BLAS.syr2k!('U', 'N', one(T), x2, ones(T, n), T(-2), xy)
    
    @inbounds for i in 1:n
        for j in 1:i
            xy[j, i] = exp(-alpha * xy[j, i])
        end
    end
    LinAlg.copytri!(xy, 'U')
end
gauss(x, 1.0)
```

compared to

```julia
kernelmatrix!(
    ColumnMajor(),
    Matrix{Float64}(n, n), 
    GaussianKernel(1.0), 
    x, true
)
```
I think one of the reasons is that `LinAlg.syrk_wrapper!` always copies the triangle in the matrix, even though you try to avoid that. I am not sure how much using `syr2k` saves.

**Comment by trthatcher** [comment]
Thanks for pointing that out - I made the change.

I played around with `syr2k` and found that it tended to be a tiny bit slower than just iterating over all the entries in the upper triangle.

**Comment by gdkrmr** [comment]
I find the performance of `MLKernels.jl` very impressive and it is very flexible, great package!

`syr2k` has a multithreaded implementation and it also depends if you use a build for a certain architecture.

**Comment by kskyten** [comment]
Should this issue be closed? It seems that removing the redundant copying operation has been pushed to master. Or is the performance of using `syr2k` under question?

**Comment by gdkrmr** [comment]
For me the call to `kernelmatrix!` is ~0.3s faster than the `gauss` function in the above example and I think that the issue is resolved. I just gave the example to illustrate the speed increase if the extra copy was avoided (and because I stumbled over `syrk2k` which is not documented), now I think this would make a great example to show how `julia` can be faster than a specialized linear algebra library, while remaining super flexible.
