### ISSUE TITLE
More detailed categorization of kernels

### ISSUE THREAD

**Issue by kskyten** [trthatcher/MLKernels.jl#49]
I think it would be useful to have a more detailed categorization of the kernels. In chapter 4 of [this book](http://www.gaussianprocess.org/gpml/chapters/RW.pdf) kernels (covariance functions) are categorized by the types of their inputs. This would enable specifying the pairwise functions in the type hierarchy instead of specifying them for each kernel separately.

For example:
- stationary kernels satisfy `K(x, y) = k(x-y)`
- isotropic kernels satisfy `K(x, y) = k(|x-y|)`

**Comment by trthatcher** [comment]
Sounds good! Very easy to add to the pairwise functions.

Could you identify which additional properties you feel are valuable and should be included?

**Comment by trthatcher** [comment]
I'm going to close this... feel free to open a new issue if you'd like any other properties.
