### ISSUE TITLE
Speed vs code clarity

### ISSUE THREAD

**Issue by st--** [trthatcher/MLKernels.jl#5]
So quite a bit of the code looks like it's rather optimised for some things - e.g. euclidean_distance() with BLAS.axpy! and BLAS.dot - is that actually that much faster than Base.dot(x, y) that it's worth it ? And what happens if x and y happen to have different lengths (_shouldn't_ happen, but you never know)? Base.dot() would just throw a DimensionMismatch. The BLAS stuff doesn't complain, just computes a different number...

On a very similar note, is it worth writing convert(T,2) instead of just 2? Doesn't the compiler automatically convert types?

And on a not so related note, but too small to bother opening a separate issue: the Coveralls thing seems to think that kernelize_scalar() for the MercerSigmoidKernel (separablekernels.jl) isn't covered - but I think it should be ? When I add a println() statement to the function, it gets printed out lots of times. Any idea what's going on?

**Comment by trthatcher** [comment]
In all honesty, I'm an amateur programmer and most of what I've learned about making things more efficient in Julia has been acquired over the past 10 weeks or less. In other words, there's a lot of crap lying around that I haven't cleaned up yet or weird habits I started off with several months ago and haven't kicked. 

So yes... Julia is pretty good at vectorizing loops. When scanning an array, it's pretty much the same speed as BLAS, but there's no fixed cost in calling the external library (I tested this recently when I was writing some of the functions in the matrixfunctions file). Base.dot should definitely be used instead, it seems to be faster anyway!

As for the convert(T,2)... I initially started doing this to ensure type stability, but I don't think it matters as long as you use integers. I'll clean these up, the convert() function is redundant.

**Comment by st--** [comment]
Just had a look at the definition of Base.dot(); it's pretty much the same as your scalar_product(), just with an added check that the two vectors have same length.

I assume the reason for having e.g. norm2() accept Array{T} rather than Vector{T} is such that you don't have to wrap rows or columns of matrices in vec(...), but that you de-facto want to accept vectors only, i.e., whatever the dimensions of x,y::Array{T}, they should be treated as 1D vectors. So instead of norm() use vecnorm()?
