### ISSUE TITLE
tag a new version

### ISSUE THREAD

**Issue by gdkrmr** [trthatcher/MLKernels.jl#50]
I am developing a package that depends on MLKernels, but the latest tagged version is 2 years old, which makes it hard to specify dependencies.

If you are interested: https://github.com/gdkrmr/KernelRidgeRegression.jl

**Comment by gdkrmr** [comment]
thanks!

**Comment by trthatcher** [comment]
Pull request for Julia `0.5` is here (`0.2` tag): https://github.com/JuliaLang/METADATA.jl/pull/10019

Nice package! Definitely going to follow that. Any papers you recommend? I was a aware of KRR but I've not read up on it.

**Comment by gdkrmr** [comment]
I can recommend the following:

Schölkopf, B., Luo, Z., Vovk, V. (Eds.), 2013. Empirical Inference. Springer Berlin Heidelberg, Berlin, Heidelberg.

Saunders, C., Gammerman, A., Vovk, V., 1998. Ridge Regression Learning Algorithm in Dual Variables, in: In Proceedings of the 15th International Conference on Machine Learning. Morgan Kaufmann, pp. 515–521.

Cristianini, N., Shawe-Taylor, J.: An Introduction to Support Vector Machines and Other
Kernel-Based Methods. Cambridge University Press, Cambridge (2000)
