### ISSUE TITLE
Issue with new release

### ISSUE THREAD

**Issue by theogf** [trthatcher/MLKernels.jl#73]
I tried to `add` the package with Julia 1.0.1 but get the following error :
```julia
(v1.0) pkg> add MLKernels
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package MLKernels [6899632a]:
 MLKernels [6899632a] log:
 ├─possible versions are: [0.0.1-0.0.3, 0.1.0, 0.2.0, 0.3.0] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.0.1-0.0.3, 0.1.0, 0.2.0, 0.3.0]
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
```

I think it has to do with the tag version in Project.toml compared to the actual github release tag

**Comment by englhardt** [comment]
The new version (v0.4.0) has not yet been pushed to https://github.com/JuliaLang/METADATA.jl. The latest version pushed to METADATA (v0.3.0) only supports Julia 0.7.

As a temporary fix you can install MLKernels directly from github by executing the following command:
```
(v1.0) pkg> add MLKernels#master
```

**Comment by theogf** [comment]
Ah I misunderstood since I saw a new release and a merge for 1.0. Thanks for the tip
