### ISSUE TITLE
Wrong metric for Matern kernel

### ISSUE THREAD

**Issue by theogf** [trthatcher/MLKernels.jl#74]
I am only half sure about what I advanced but I think the metric used for the Matern Kernel is not correct. Currently it is using a Squared Euclidean (hence ||x-x'||^2).
But in the documentation (and in the definition of the Matern kernel according to Rasmussen and Williams) the distance used is the Euclidean distance (||x-x'||), also in the documentation the equation of Matern kernel should have the 2's in the square roots.

**Comment by trthatcher** [comment]
Thanks for catching this!
