### ISSUE TITLE
Memory usage / in-place covariance matrix calculations

### ISSUE THREAD

**Issue by st--** [trthatcher/MLKernels.jl#8]
Reading up on Coverage.jl I was curious to check the memory allocation behaviour of the code. Most of it is constructing Kernels, which I think is fine. But it occurred to me that e.g. the second derivatives construct n x n matrices, and memory allocation is one of the biggest speed hits. So in the future it might be worth rewriting the kernel functions such that they can write directly into the covariance matrix. (This will require some more careful thought, and isn't urgent, but I wanted to bring it up now before I forget again!)

**Comment by st--** [comment]
Also, at least in Julia v0.3, slicing arrays seems to construct copies, so passing X[i,:] to kernel() which then calls sqdist on that is inefficient, and for larger matrices it's much more efficient to pass the whole X (which is then just a pointer) plus indices and do the sqdist loop by hand. Obviously more cumbersome, but I'll think about how to write a `@sqdist(X[i,:], Y[i,:])` macro which replaces the colons with the iteration index.

**Comment by trthatcher** [comment]
Out of curiosity, I noticed in your implementation of kernel_dxdy you allocated an array using K = Array(T, d, n, d, m) rather than Array(T, d, d, n, m). How come you wanted to stagger the columns of the (x-y)(x-y)' submatrices?

**Comment by st--** [comment]
Because the final derivative covariance matrix is a (n*d) by (m*d) object; I don't care how the sub-blocks are laid out in memory (as long as it's consistent!), but I want to be able to reshape it into (n*d, m*d). If it's Array(T, d, d, n, m), I'd have to permute the dimensions first, which requires re-constructing the matrix and makes it - for my use case unnecessarily - slower.

**Comment by trthatcher** [comment]
Haha, I don't doubt it... I was curious as to why it comes out to that shape. I would expect the mixed derivative with respect to two matrices to be sort of an... n by m matrix of d by d matrices. However, it depends on how you're using it. I've scanned through the readings you pointed me to last week, but I didn't see anything related to training from/predicting of derivatives of function values that you were looking to use them for. Do you have anything on that? I'm curious about the application (:

On a related note, I finished off your kernel_dxdy function for transposed data matrices... I was able to shave off a few percent (at least in my tests) by breaking a few pieces out. What are your tests looking like? How much RAM does your machine have? Mine runs out of RAM pretty fast...
